pipeline {
    agent none
    stages{
        stage('testing python'){
            when {
                changeset '**/vote/**'
            }
            agent {
                docker {
                    image 'python:2.7-alpine'
                    args '-u root --privileged'
                }
            }
            steps{
                echo 'Building vote app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests tests.module'
                }
            }
        }
    }
    post{
        always{            
            echo 'Result multibranch pipeline completed'
        }
        failure{
            slackSend (message: "Build failed: ${env.JOB_NAME} ${BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success{
            slackSend (message: "Build sucess: ${env.JOB_NAME} ${BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}