pipeline {
    agent none
    stages{
        stage('testing python'){
            when {
                changeset '**/vote/**'
            }
            agent {
                docker {
                    image 'eeganlf/voteapp-python:v0.1.0'
                }
            }
            steps{
                echo 'Building vote app'
                sh 'python --version'
                sh 'which python'
            }
        }
    }
    post{
        always{            
            echo 'Result multibranch pipeline completed'
        }
        failure{
            slackSend (message: "Build failed: ${env.JOB_NAME} ${BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success{
            slackSend (message: "Build sucess: ${env.JOB_NAME} ${BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}